query ($id: ID!, $type: String) {
  article(id: $id, type: $type) {
    id
    title
    summary
    status
    cover {
      path
      name
      ext
      description
      size
    }
    author
    publishDate(format:"YYYY-MM-DD HH:mm:ss")
    category {
      id
      name
    }
    content
    metaData {
      title
      description
    }
    tags
    sn
    push {
      id
      sex
      msgType
      msgId
      msgTitle
      minAge
      maxAge
      acquiredTypes
      chronicTypes
      pushDate
    }
    uuid
    creator
    modifier
    createTime
    modifyTime
  }
}