language: node_js
node_js:
  - "7"

cache:
  yarn: true
  directories:
    - "node_modules"

install:
  - yarn
  - yarn global add codecov
  - yarn global add codacy-coverage
  
script:
  - node scripts/test.js --env=jsdom --coverage
  - codecov
  - cat coverage/lcov.info | codacy-coverage

deploy:
  script:
    - yarn build
  local_dir: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: deploy-ghpages