language: node_js
node_js:
  - "7"

cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - yarn build

deploy:
  local_dir: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: deploy-ghpages