language: node_js
node_js:
  - "7"

cache:
  yarn: true
  directories:
    - "node_modules"

install:
  - yarn global add codecov
  
script:
  - yarn test --coverage
  - codecov

deploy:
  script:
    - yarn build
  local_dir: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: deploy-ghpages