mutation ($username: String!, $password: String) {
  login(username: $username, password: $password, scope: user) {
    id
    nickName
    profile {
      name
      mobile
    }
    roles
    token(clientId:"ff80808155005dfb0155005e4fb90000"){
      accessToken
      refreshToken
      tokenCreationTime
      reExpiresIn
      expiresIn
    }
  }
}